# Specify version format
version: "{build}-{branch}"

# Build worker image (VM template)
image: Visual Studio 2019

# Build platform, i.e. Win32, x64.
platform:
    - x64

# Scripts that are called at very beginning, before repo cloning
init:
    - curl https://bootstrap.pypa.io/get-pip.py --output getpip.py
    - choco install python --version 3.9.2
    - C:\Python39-x64\python.exe --version
    - C:\Python39-x64\python.exe getpip.py

# Scripts that run after cloning repository
install:
    - C:\Python39-x64\python.exe -m pip install -r requirements.txt
    - C:\Python39-x64\python.exe -m pip install pyinstaller

build_script:
    - C:\Python39-x64\python.exe build.py

artifacts:
    - path: build\*.zip
      name: Build Files
      type: zip

deploy:
    provider: GitHub
    auth_token:
        secure: nCEK3ggRnABshEsWDPG17mDPKAnQPiQGd3KImvAqeK7m3ohhOzszXhbejJb1292W
    artifact: build\*.zip
    draft: false
    prerelease: false
    on:
        branch: master # release from master branch only
        APPVEYOR_REPO_TAG: true # deploy on tag push only
