# Specify version format
version: "{build}-{branch}"

# Build worker image (VM template)
image: Visual Studio 2019

# Build platform, i.e. Win32, x64.
platform:
    - x64

# Scripts that run after cloning repository
install:
    - curl https://bootstrap.pypa.io/get-pip.py --output getpip.py
    - choco install python --version 3.9.2
    - C:\Python39-x64\python.exe --version
    - C:\Python39-x64\python.exe getpip.py
    - C:\Python39-x64\python.exe -m pip install -r requirements.txt
    - C:\Python39-x64\python.exe -m pip install "pyinstaller==4.4"

build_script:
    - C:\Python39-x64\python.exe build.py -O2
    - C:\Python39-x64\python.exe build.py -O2 --onefile --output_dir build_onefile

artifacts:
    - path: build\bin\*.exe
      name: Installer
      type: exe
    - path: build_onefile\bin\*.zip
      name: ZipFile
      type: zip

deploy:
    tag: $(APPVEYOR_REPO_TAG_NAME)
    provider: GitHub
    release: Release $(APPVEYOR_REPO_TAG_NAME)
    description: |
        Created automatically by AppVeyor.
        https://ci.appveyor.com/project/edoren/edobot/builds/$(APPVEYOR_BUILD_ID)
    auth_token:
        secure: nCEK3ggRnABshEsWDPG17mDPKAnQPiQGd3KImvAqeK7m3ohhOzszXhbejJb1292W
    artifact: /.*\.(zip|exe)/
    force_update: true
    on:
        # https://www.appveyor.com/docs/deployment/#deploy-on-tag-github-and-gitlab-only
        APPVEYOR_REPO_TAG: true
