language: python
jobs:
    include:
        # ======= OSX ========
        - name: "Python 3.9.2 on macOS 10.15.7"
          os: osx
          osx_image: xcode12.2
          language: shell
          before_install:
              - unset PYENV_ROOT
              - curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
              - export PATH="$HOME/.pyenv/bin:$PATH"
              - eval "$(pyenv init -)"
              - pyenv update
              - pyenv install --list
              - env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.9.2
              - pyenv global 3.9.2
              - python --version
              - pip install --upgrade pip
        # ====== WINDOWS =========
        - name: "Python 3.9.2 on Windows"
          os: windows
          language: shell
          before_install:
              - choco install python --version 3.9.2
              - python --version
              - python -m pip install --upgrade pip
          env: PATH=/c/Python39:/c/Python39/Scripts:$PATH
install:
    - pip install -r requirements.txt
    - pip install pyinstaller
script:
    - python build.py
